// =============================================================================
// Chat Archive — Content Script (Built)
// =============================================================================
// Auto-generated by build.sh. Do not edit directly — edit files in src/ instead.
//
// Phase 2: Pass 0 clipboard extraction (all 5 platforms) + Pass 1 heuristics
//          + JSON & Markdown export
//
// Zero network. Zero telemetry. Conversations never leave your browser.
// =============================================================================

(function() {
'use strict';


// --- src/utils/constants.js ---
// =============================================================================
// Chat Archive — Constants & Shared Utilities
// =============================================================================

// --- Execution Limits (Anti-Runaway Circuit Breakers) ---
const SAFETY_LIMITS = {
  MAX_TURNS: 500,
  MAX_SCROLL_ITERATIONS: 100,
  MAX_EXTRACTION_TIME_MS: 60_000,
  MAX_CLIPBOARD_WAIT_MS: 2_000,
  MAX_SINGLE_TURN_SIZE: 100_000,
  SCROLL_STABILITY_THRESHOLD: 3,
  CLIPBOARD_READ_DELAY_MS: 175,
  SCROLL_STEP_DELAY_MS: 300,
  HOVER_SETTLE_MS: 50,
};

const SCHEMA_VERSION = '1.0';
const EXTENSION_VERSION = '0.8.2';

// --- Platform Detection ---
function detectPlatform() {
  const host = window.location.hostname;
  const path = window.location.pathname;

  if (host === 'claude.ai') return 'claude';
  if (host === 'chatgpt.com' || host === 'chat.openai.com') return 'chatgpt';
  if (host === 'gemini.google.com') return 'gemini';
  if (host === 'grok.com') return 'grok';
  if (host === 'x.com' && path.startsWith('/i/grok')) return 'grok-x';
  if (host === 'perplexity.ai' || host === 'www.perplexity.ai') return 'perplexity';
  return null;
}

function platformToDisplayName(platform) {
  const names = {
    claude: 'claude.ai',
    chatgpt: 'chatgpt.com',
    gemini: 'gemini.google.com',
    grok: 'grok.com',
    'grok-x': 'x.com/i/grok',
    perplexity: 'perplexity.ai',
  };
  return names[platform] || platform;
}

// --- Shared DOM Utilities ---

function wait(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/**
 * Wait for conversation DOM to be ready before extraction.
 * Polls for platform-specific conversation elements.
 * Returns { ready: true } when found, or { ready: false, error: 'timeout' } after timeout.
 */
async function waitForConversationReady(options = {}) {
  const timeoutMs = options.timeout || 15000;
  const pollIntervalMs = options.pollInterval || 400;
  const platform = detectPlatform();
  
  if (!platform) {
    return { ready: false, error: 'Not on a supported platform' };
  }

  const selectors = {
    chatgpt: 'article[data-testid^="conversation-turn-"]',
    claude: '[data-testid="user-message"], .font-claude-message',
    gemini: 'user-query, model-response',
    grok: '[class*="message"], [data-testid*="message"]',
    'grok-x': '[data-testid*="message"], [class*="message"]',
    perplexity: 'button[data-testid="copy-query-button"], .prose.text-pretty',
  };

  const selector = selectors[platform];
  if (!selector) {
    return { ready: false, error: `No selector for platform: ${platform}` };
  }

  const startTime = Date.now();
  
  while (Date.now() - startTime < timeoutMs) {
    const element = document.querySelector(selector);
    if (element) {
      console.log(`[ChatVault] Conversation ready after ${Date.now() - startTime}ms`);
      return { ready: true, waitedMs: Date.now() - startTime };
    }
    await wait(pollIntervalMs);
  }

  console.warn(`[ChatVault] Conversation not ready after ${timeoutMs}ms timeout`);
  return { ready: false, error: 'timeout', waitedMs: timeoutMs };
}

/**
 * Test if clipboard read access is available.
 * Some browsers block navigator.clipboard.readText() in extension contexts.
 */
async function testClipboardAccess() {
  try {
    await navigator.clipboard.readText();
    return true;
  } catch {
    return false;
  }
}

/**
 * Fuzzy button finder — resilient to selector changes.
 * Searches by aria-label, title, data-testid, and tooltip text.
 */
function findActionButton(container, intent) {
  // intent: 'copy', 'edit', 'copy text', 'copy prompt', etc.
  const intents = Array.isArray(intent) ? intent : [intent];

  for (const label of intents) {
    const strategies = [
      // Strategy 1: exact aria-label (most stable — user-facing)
      () => container.querySelector(`button[aria-label="${label}"]`),
      // Strategy 2: case-insensitive aria-label contains
      () => container.querySelector(`button[aria-label*="${label}" i]`),
      // Strategy 3: data-testid containing intent
      () => container.querySelector(`button[data-testid*="${label.toLowerCase().replace(/\s+/g, '-')}"]`),
      // Strategy 4: title attribute
      () => container.querySelector(`button[title*="${label}" i]`),
      // Strategy 5: mattooltip (Angular Material)
      () => container.querySelector(`button[mattooltip*="${label}" i]`),
    ];

    for (const strategy of strategies) {
      try {
        const result = strategy();
        if (result) return result;
      } catch {
        // Selector syntax error — skip
      }
    }
  }
  return null;
}

/**
 * Click a copy button and read the resulting clipboard content.
 * Returns the clipboard text, or null on failure.
 */
async function clickCopyAndRead(button) {
  if (!button) return null;

  try {
    // Snapshot current clipboard to detect change
    let previous = '';
    try {
      previous = await navigator.clipboard.readText();
    } catch {
      // Clipboard empty or inaccessible — ok, we'll still try
    }

    button.click();
    await wait(SAFETY_LIMITS.CLIPBOARD_READ_DELAY_MS);

    const content = await navigator.clipboard.readText();

    // Verify we got something (and ideally something different)
    if (content && content.length > 0) {
      return content;
    }
    return null;
  } catch {
    return null;
  }
}

/**
 * Scroll a container to load all lazy-loaded content.
 * Returns the number of scroll iterations performed.
 */
async function scrollToLoadAll(scrollContainer, countSelector, startTime) {
  let previousCount = 0;
  let stableIterations = 0;
  let scrollIterations = 0;

  const initialScrollHeight = scrollContainer.scrollHeight;
  console.log(`[Chat Archive] Scroll: Initial height=${initialScrollHeight}, clientHeight=${scrollContainer.clientHeight}`);
  
  scrollContainer.scrollTop = 0;
  await wait(500);

  while (
    stableIterations < SAFETY_LIMITS.SCROLL_STABILITY_THRESHOLD &&
    scrollIterations < SAFETY_LIMITS.MAX_SCROLL_ITERATIONS
  ) {
    if (startTime && Date.now() - startTime > SAFETY_LIMITS.MAX_EXTRACTION_TIME_MS) break;

    const currentElements = document.querySelectorAll(countSelector);
    const currentCount = currentElements.length;
    console.log(`[Chat Archive] Scroll iteration ${scrollIterations}: found ${currentCount} elements (prev: ${previousCount}), stable: ${stableIterations}`);
    
    if (currentCount === previousCount) {
      stableIterations++;
    } else {
      stableIterations = 0;
      previousCount = currentCount;
    }

    const scrollAmount = scrollContainer.clientHeight * 0.8;
    console.log(`[Chat Archive] Scrolling by ${scrollAmount}px, current scrollTop: ${scrollContainer.scrollTop}`);
    scrollContainer.scrollBy(0, scrollAmount);
    await wait(SAFETY_LIMITS.SCROLL_STEP_DELAY_MS);
    scrollIterations++;
  }

  // Scroll back to top for clean state
  scrollContainer.scrollTop = 0;
  await wait(200);

  console.log(`[Chat Archive] Scroll complete: ${previousCount} elements after ${scrollIterations} scrolls`);
  return scrollIterations;
}

/**
 * Find the scrollable ancestor of a given element.
 */
function findScrollableAncestor(element) {
  let parent = element.parentElement;
  while (parent) {
    const style = window.getComputedStyle(parent);
    if (style.overflowY === 'scroll' || style.overflowY === 'auto') {
      return parent;
    }
    parent = parent.parentElement;
  }
  return null;
}

/**
 * Flag a turn for size if needed, mutates the turn object.
 */
function flagIfOversized(turn) {
  if (turn.content && turn.content.length > SAFETY_LIMITS.MAX_SINGLE_TURN_SIZE) {
    turn.flagged = true;
    turn.flagReason = 'Content exceeds 100KB';
  }
  return turn;
}


// --- src/extractors/claude.js ---
// =============================================================================
// Chat Archive — Claude.ai Extractor (Pass 0 + Direct Text Fallback)
// =============================================================================
// Architecture: Appendix C
// Turn container: div[data-test-render-count] wraps user+assistant pair
// Copy buttons: button[data-testid="action-bar-copy"] on both roles
// Role signals: [data-testid="user-message"] (user), [data-is-streaming] (assistant)

async function extractClaudeConversation() {
  const startTime = Date.now();
  const turns = [];
  const errors = [];

  // 1. Find scroll container
  const scrollContainer = findClaudeScrollContainer();
  if (!scrollContainer) {
    return { turns: [], errors: ['Scroll container not found'], partial: true };
  }

  // 2. Load all turns via scrolling
  await scrollToLoadAll(scrollContainer, '[data-test-render-count]', startTime);

  // 3. Get turn pair containers
  const turnContainers = document.querySelectorAll('[data-test-render-count]');
  console.log(`[Chat Archive] Claude: Found ${turnContainers.length} turn containers`);

  if (turnContainers.length === 0) {
    return { turns: [], errors: ['No turn containers found'], partial: true };
  }

  // 4. Test clipboard access
  const hasClipboard = await testClipboardAccess();
  console.log(`[Chat Archive] Claude: Clipboard access: ${hasClipboard}`);

  // 5. Extract each turn pair
  for (let i = 0; i < turnContainers.length; i++) {
    if (Date.now() - startTime > SAFETY_LIMITS.MAX_EXTRACTION_TIME_MS) {
      errors.push(`Extraction timed out after ${SAFETY_LIMITS.MAX_EXTRACTION_TIME_MS}ms`);
      break;
    }
    if (turns.length >= SAFETY_LIMITS.MAX_TURNS) {
      errors.push(`Hit maximum turn limit (${SAFETY_LIMITS.MAX_TURNS})`);
      break;
    }

    const container = turnContainers[i];

    try {
      // Scroll into view to ensure content is rendered
      container.scrollIntoView({ behavior: 'instant', block: 'center' });
      await wait(150);

      // Extract user turn
      const userTurn = await extractClaudeTurn(container, 'user', hasClipboard);
      if (userTurn) turns.push(flagIfOversized(userTurn));

      // Extract assistant turn
      const assistantTurn = await extractClaudeTurn(container, 'assistant', hasClipboard);
      if (assistantTurn) turns.push(flagIfOversized(assistantTurn));
    } catch (err) {
      errors.push(`Error extracting container ${i}: ${err.message}`);
      console.warn(`[Chat Archive] Claude: Error on container ${i}:`, err);
    }
  }

  console.log(`[Chat Archive] Claude: Extracted ${turns.length} turns, ${errors.length} errors`);
  return { turns, errors, partial: errors.length > 0 };
}

/**
 * Extract a single turn (user or assistant) from a turn-pair container.
 * Pass 0: Try copy button → clipboard. Fallback: direct text extraction.
 */
async function extractClaudeTurn(container, role, hasClipboard) {
  // Determine which sub-element to target
  const roleSelector = role === 'user'
    ? '[data-testid="user-message"]'
    : '[data-is-streaming]';

  // Fallback role selector
  const fallbackSelector = role === 'user'
    ? '.font-user-message'
    : '.font-claude-response';

  const roleElement = container.querySelector(roleSelector)
    || container.querySelector(fallbackSelector);

  if (!roleElement) return null;

  // Find the nearest group container (for hover-triggering copy button visibility)
  const groupContainer = roleElement.closest('.group') || roleElement;

  let content = null;
  let extractionMethod = 'direct';

  // --- Pass 0: Clipboard via copy button ---
  if (hasClipboard) {
    try {
      // Trigger hover to ensure button is interactable
      groupContainer.dispatchEvent(new MouseEvent('mouseenter', { bubbles: true }));
      await wait(SAFETY_LIMITS.HOVER_SETTLE_MS);

      // Find copy button within this turn's group
      // Claude uses data-testid="action-bar-copy" — but each turn-pair has multiple
      // We need the copy button closest to our role element
      const copyButton = findClaudeCopyButton(groupContainer, container, role);

      if (copyButton) {
        const clipboardContent = await clickCopyAndRead(copyButton);
        if (clipboardContent && clipboardContent.trim().length > 0) {
          content = clipboardContent;
          extractionMethod = 'clipboard';
        }
      }

      groupContainer.dispatchEvent(new MouseEvent('mouseleave', { bubbles: true }));
    } catch (err) {
      console.warn(`[Chat Archive] Claude: Clipboard extraction failed for ${role}:`, err);
    }
  }

  // --- Fallback: Direct text extraction ---
  if (!content) {
    content = extractClaudeDirectText(container, role);
    extractionMethod = 'direct';
  }

  if (!content || content.trim().length === 0) return null;

  // Timestamp
  const timestampEl = container.querySelector('span.text-text-500.text-xs');
  const timestamp = timestampEl?.textContent?.trim() || undefined;

  return {
    role,
    content: content.trim(),
    timestamp,
    extractionMethod,
    confidence: 0.95,
    classificationSource: 'structural',
  };
}

/**
 * Find the correct copy button for a specific role within a turn-pair container.
 * Each data-test-render-count container has TWO groups (user + assistant),
 * each with their own action bar and copy button.
 */
function findClaudeCopyButton(groupContainer, pairContainer, role) {
  // Try within the immediate group first
  let btn = groupContainer.querySelector('button[data-testid="action-bar-copy"]');
  if (btn) return btn;

  btn = findActionButton(groupContainer, ['Copy']);
  if (btn) return btn;

  // If group didn't have it, search all copy buttons in the pair container
  // and match by proximity to the role element
  const allCopyBtns = pairContainer.querySelectorAll('button[data-testid="action-bar-copy"]');
  if (allCopyBtns.length === 0) return null;

  if (allCopyBtns.length === 1) return allCopyBtns[0];

  // Multiple copy buttons — pick by position:
  // First copy button belongs to user, second to assistant
  if (role === 'user') return allCopyBtns[0];
  if (role === 'assistant') return allCopyBtns[allCopyBtns.length - 1];

  return allCopyBtns[0];
}

/**
 * Direct text extraction fallback for Claude.
 */
function extractClaudeDirectText(container, role) {
  if (role === 'user') {
    const el = container.querySelector('[data-testid="user-message"]');
    return el?.textContent?.trim() || '';
  } else {
    // Prefer .standard-markdown within .font-claude-response
    const markdown = container.querySelector('.font-claude-response .standard-markdown');
    if (markdown) return markdown.textContent?.trim() || '';

    const response = container.querySelector('.font-claude-response');
    if (response) return response.textContent?.trim() || '';

    const streaming = container.querySelector('[data-is-streaming]');
    return streaming?.textContent?.trim() || '';
  }
}

/**
 * Find Claude's scrollable chat container.
 */
function findClaudeScrollContainer() {
  const strategies = [
    () => document.querySelector('.overflow-y-scroll.overflow-x-hidden.pt-6.flex-1'),
    () => {
      const scrollables = document.querySelectorAll('[class*="overflow-y-scroll"]');
      for (const el of scrollables) {
        if (el.querySelector('[data-test-render-count]')) return el;
      }
      return null;
    },
    () => {
      const firstTurn = document.querySelector('[data-test-render-count]');
      return firstTurn ? findScrollableAncestor(firstTurn) : null;
    },
  ];

  for (const strategy of strategies) {
    const result = strategy();
    if (result) return result;
  }
  return null;
}


// --- src/extractors/chatgpt.js ---
// =============================================================================
// Chat Archive — ChatGPT Extractor (Pass 0 + Direct Text Fallback)
// =============================================================================
// Architecture: Appendix E
// Turn container: article[data-testid="conversation-turn-{N}"] — one per turn (flat)
// Copy button: button[data-testid="copy-turn-action-button"] on both roles
// Role signals: data-turn="user"|"assistant" on <article> (0.99)
//               data-message-author-role="user"|"assistant" (0.99)

async function extractChatGPTConversation() {
  const startTime = Date.now();
  const turns = [];
  const errors = [];

  // 1. Find scroll container
  const scrollContainer = findChatGPTScrollContainer();
  if (!scrollContainer) {
    return { turns: [], errors: ['Scroll container not found'], partial: true };
  }

  // 2. Load all turns
  await scrollToLoadAll(
    scrollContainer,
    'article[data-testid^="conversation-turn-"]',
    startTime
  );

  // 3. Get all articles
  const articles = document.querySelectorAll('article[data-testid^="conversation-turn-"]');
  console.log(`[Chat Archive] ChatGPT: Found ${articles.length} turn articles`);

  if (articles.length === 0) {
    return { turns: [], errors: ['No turn articles found'], partial: true };
  }

  // 4. Skip clipboard for ChatGPT: clicking Copy triggers "Failed to copy to clipboard" toasts
  //    and can fail in extension context. Use direct text extraction only.
  const hasClipboard = false;

  // 5. Extract each article
  for (let i = 0; i < articles.length; i++) {
    if (Date.now() - startTime > SAFETY_LIMITS.MAX_EXTRACTION_TIME_MS) {
      errors.push(`Extraction timed out after ${SAFETY_LIMITS.MAX_EXTRACTION_TIME_MS}ms`);
      break;
    }
    if (turns.length >= SAFETY_LIMITS.MAX_TURNS) {
      errors.push(`Hit maximum turn limit (${SAFETY_LIMITS.MAX_TURNS})`);
      break;
    }

    const article = articles[i];

    try {
      article.scrollIntoView({ behavior: 'instant', block: 'center' });
      await wait(150);

      const turn = await extractChatGPTTurn(article, hasClipboard);
      if (turn) turns.push(flagIfOversized(turn));
    } catch (err) {
      errors.push(`Error extracting turn ${i}: ${err.message}`);
      console.warn(`[Chat Archive] ChatGPT: Error on turn ${i}:`, err);
    }
  }

  console.log(`[Chat Archive] ChatGPT: Extracted ${turns.length} turns, ${errors.length} errors`);
  return { turns, errors, partial: errors.length > 0 };
}

async function extractChatGPTTurn(article, hasClipboard) {
  // --- Role detection (multiple high-confidence signals) ---
  let role = article.getAttribute('data-turn'); // 'user' or 'assistant'

  if (!role) {
    // Fallback: data-message-author-role
    const msgDiv = article.querySelector('[data-message-author-role]');
    role = msgDiv?.getAttribute('data-message-author-role');
  }

  if (!role) {
    // Fallback: screen reader heading
    const h5 = article.querySelector('h5.sr-only');
    const h6 = article.querySelector('h6.sr-only');
    if (h5 && h5.textContent?.includes('You said')) role = 'user';
    else if (h6 && h6.textContent?.includes('ChatGPT said')) role = 'assistant';
  }

  if (role !== 'user' && role !== 'assistant') return null;

  // --- Turn metadata ---
  const testId = article.getAttribute('data-testid') || '';
  const turnNumber = parseInt(testId.replace('conversation-turn-', '')) || 0;
  const turnId = article.getAttribute('data-turn-id') || '';
  const msgDiv = article.querySelector('[data-message-author-role]');
  const modelSlug = msgDiv?.getAttribute('data-message-model-slug') || undefined;

  // --- Pass 0: Clipboard extraction ---
  let content = null;
  let extractionMethod = 'direct';

  if (hasClipboard) {
    try {
      const copyBtn = article.querySelector('button[data-testid="copy-turn-action-button"]');
      if (!copyBtn) {
        // Fuzzy fallback
        const fallback = findActionButton(article, ['Copy']);
        if (fallback) {
          const clipContent = await clickCopyAndRead(fallback);
          if (clipContent && clipContent.trim().length > 0) {
            content = clipContent;
            extractionMethod = 'clipboard';
          }
        }
      } else {
        const clipContent = await clickCopyAndRead(copyBtn);
        if (clipContent && clipContent.trim().length > 0) {
          content = clipContent;
          extractionMethod = 'clipboard';
        }
      }
    } catch (err) {
      console.warn(`[Chat Archive] ChatGPT: Clipboard failed for turn ${turnNumber}:`, err);
    }
  }

  // --- Fallback: Direct text ---
  if (!content) {
    content = extractChatGPTDirectText(article, role);
    extractionMethod = 'direct';
  }

  if (!content || content.trim().length === 0) return null;

  return {
    role,
    content: content.trim(),
    turnNumber,
    turnId,
    modelSlug,
    extractionMethod,
    confidence: 0.99, // data-turn attribute is extremely reliable
    classificationSource: 'structural',
  };
}

function extractChatGPTDirectText(article, role) {
  if (role === 'user') {
    const el = article.querySelector('.whitespace-pre-wrap');
    return el?.textContent?.trim() || '';
  } else {
    // Try .markdown.prose first, then broader selectors
    const markdown = article.querySelector('.markdown.prose');
    if (markdown) return markdown.textContent?.trim() || '';

    const markdownNew = article.querySelector('.markdown');
    if (markdownNew) return markdownNew.textContent?.trim() || '';

    // Last resort: grab all text from the message div
    const msgDiv = article.querySelector('[data-message-author-role="assistant"]');
    return msgDiv?.textContent?.trim() || '';
  }
}

function findChatGPTScrollContainer() {
  const strategies = [
    () => document.querySelector('[data-scroll-root]'),
    () => {
      const firstArticle = document.querySelector('article[data-testid^="conversation-turn-"]');
      return firstArticle ? findScrollableAncestor(firstArticle) : null;
    },
    () => document.querySelector('main [class*="overflow-y-auto"]'),
  ];

  for (const strategy of strategies) {
    const result = strategy();
    if (result) return result;
  }
  return null;
}


// --- src/extractors/gemini.js ---
// =============================================================================
// Chat Archive — Gemini Extractor (Pass 0 + Direct Text Fallback)
// =============================================================================
// Architecture: Appendix D
// Turn container: div.conversation-container[id] wraps <user-query> + <model-response>
// Copy buttons: aria-label="Copy prompt" (user), data-test-id="copy-button" (assistant)
// Role signals: <user-query> (0.99), <model-response> (0.99)

async function extractGeminiConversation() {
  const startTime = Date.now();
  const turns = [];
  const errors = [];

  // 1. Find scroll container
  const scrollContainer = findGeminiScrollContainer();
  if (!scrollContainer) {
    return { turns: [], errors: ['Scroll container not found'], partial: true };
  }

  // 2. Load all turns
  await scrollToLoadAll(
    scrollContainer,
    'div.conversation-container[id]',
    startTime
  );

  // 3. Get turn containers
  const turnContainers = document.querySelectorAll('div.conversation-container[id]');
  console.log(`[Chat Archive] Gemini: Found ${turnContainers.length} turn containers`);

  if (turnContainers.length === 0) {
    // Fallback: try older selectors
    const oldContainers = document.querySelectorAll('ms-chat-turn');
    if (oldContainers.length > 0) {
      console.log(`[Chat Archive] Gemini: Found ${oldContainers.length} legacy ms-chat-turn elements`);
      return extractGeminiLegacy(oldContainers, startTime);
    }
    return { turns: [], errors: ['No turn containers found'], partial: true };
  }

  // 4. Clipboard test
  const hasClipboard = await testClipboardAccess();
  console.log(`[Chat Archive] Gemini: Clipboard access: ${hasClipboard}`);

  // 5. Extract each turn pair
  for (let i = 0; i < turnContainers.length; i++) {
    if (Date.now() - startTime > SAFETY_LIMITS.MAX_EXTRACTION_TIME_MS) {
      errors.push(`Extraction timed out after ${SAFETY_LIMITS.MAX_EXTRACTION_TIME_MS}ms`);
      break;
    }
    if (turns.length >= SAFETY_LIMITS.MAX_TURNS) {
      errors.push(`Hit maximum turn limit (${SAFETY_LIMITS.MAX_TURNS})`);
      break;
    }

    const container = turnContainers[i];
    const turnId = container.id;

    try {
      container.scrollIntoView({ behavior: 'instant', block: 'center' });
      await wait(200);

      // --- User turn ---
      const userQuery = container.querySelector('user-query');
      if (userQuery) {
        const userTurn = await extractGeminiUserTurn(userQuery, turnId, hasClipboard);
        if (userTurn) turns.push(flagIfOversized(userTurn));
      }

      // --- Assistant turn ---
      const modelResponse = container.querySelector('model-response');
      if (modelResponse) {
        const assistantTurn = await extractGeminiAssistantTurn(modelResponse, turnId, hasClipboard);
        if (assistantTurn) turns.push(flagIfOversized(assistantTurn));
      }
    } catch (err) {
      errors.push(`Error extracting container ${i} (${turnId}): ${err.message}`);
      console.warn(`[Chat Archive] Gemini: Error on container ${i}:`, err);
    }
  }

  console.log(`[Chat Archive] Gemini: Extracted ${turns.length} turns, ${errors.length} errors`);
  return { turns, errors, partial: errors.length > 0 };
}

async function extractGeminiUserTurn(userQuery, turnId, hasClipboard) {
  let content = null;
  let extractionMethod = 'direct';

  // Pass 0: Copy button
  if (hasClipboard) {
    try {
      const copyBtn = userQuery.querySelector('button[aria-label="Copy prompt"]')
        || findActionButton(userQuery, ['Copy prompt', 'Copy']);
      if (copyBtn) {
        const clipContent = await clickCopyAndRead(copyBtn);
        if (clipContent && clipContent.trim().length > 0) {
          content = clipContent;
          extractionMethod = 'clipboard';
        }
      }
    } catch (err) {
      console.warn(`[Chat Archive] Gemini: User clipboard failed:`, err);
    }
  }

  // Fallback: direct text
  if (!content) {
    const textEl = userQuery.querySelector('.query-text-line');
    content = textEl?.textContent?.trim() || '';

    // Broader fallback
    if (!content) {
      const queryText = userQuery.querySelector('.query-text');
      content = queryText?.textContent?.trim() || '';
    }
    if (!content) {
      content = userQuery.textContent?.trim() || '';
    }
    extractionMethod = 'direct';
  }

  if (!content || content.trim().length === 0) return null;

  return {
    role: 'user',
    content: content.trim(),
    turnId,
    extractionMethod,
    confidence: 0.99,
    classificationSource: 'structural',
  };
}

async function extractGeminiAssistantTurn(modelResponse, turnId, hasClipboard) {
  let content = null;
  let extractionMethod = 'direct';

  // Pass 0: Copy button
  if (hasClipboard) {
    try {
      const copyBtn = modelResponse.querySelector('button[data-test-id="copy-button"]')
        || modelResponse.querySelector('button[aria-label="Copy"]')
        || findActionButton(modelResponse, ['Copy']);
      if (copyBtn) {
        const clipContent = await clickCopyAndRead(copyBtn);
        if (clipContent && clipContent.trim().length > 0) {
          content = clipContent;
          extractionMethod = 'clipboard';
        }
      }
    } catch (err) {
      console.warn(`[Chat Archive] Gemini: Assistant clipboard failed:`, err);
    }
  }

  // Fallback: direct text (with citation stripping)
  if (!content) {
    content = extractGeminiAssistantDirectText(modelResponse);
    extractionMethod = 'direct';
  }

  if (!content || content.trim().length === 0) return null;

  return {
    role: 'assistant',
    content: content.trim(),
    turnId,
    extractionMethod,
    confidence: 0.99,
    classificationSource: 'structural',
  };
}

/**
 * Direct text extraction for Gemini assistant messages.
 * Clones the element and strips citations, avatars, processing states.
 */
function extractGeminiAssistantDirectText(modelResponse) {
  const markdown = modelResponse.querySelector('.markdown.markdown-main-panel');
  if (!markdown) {
    // Broader fallback
    const messageContent = modelResponse.querySelector('message-content');
    if (messageContent) {
      const clone = messageContent.cloneNode(true);
      stripGeminiDecorations(clone);
      return clone.textContent?.trim() || '';
    }
    return modelResponse.textContent?.trim() || '';
  }

  const clone = markdown.cloneNode(true);
  stripGeminiDecorations(clone);
  return clone.textContent?.trim() || '';
}

/**
 * Remove decorative/non-content elements from a Gemini DOM clone.
 */
function stripGeminiDecorations(element) {
  const selectorsToRemove = [
    'source-footnote',
    'source-inline-chip',
    'sources-carousel-inline',
    'bard-avatar',
    'processing-state',
    'tts-control',
    'thumb-up-button',
    'thumb-down-button',
    'copy-button',
    '.code-block-decoration',
    'freemium-rag-disclaimer',
    'sensitive-memories-banner',
  ];

  for (const selector of selectorsToRemove) {
    try {
      element.querySelectorAll(selector).forEach((el) => el.remove());
    } catch {
      // Invalid selector — skip
    }
  }
}

/**
 * Legacy Gemini extraction for older DOM structure (ms-chat-turn).
 */
async function extractGeminiLegacy(turnElements, startTime) {
  const turns = [];
  const errors = [];

  for (let i = 0; i < turnElements.length; i++) {
    if (Date.now() - startTime > SAFETY_LIMITS.MAX_EXTRACTION_TIME_MS) break;
    if (turns.length >= SAFETY_LIMITS.MAX_TURNS) break;

    try {
      const el = turnElements[i];
      const content = el.textContent?.trim() || '';
      if (!content) continue;

      // Legacy role detection: alternating pattern
      turns.push({
        role: i % 2 === 0 ? 'user' : 'assistant',
        content,
        extractionMethod: 'direct',
        confidence: 0.60,
        classificationSource: 'heuristic-alternation',
      });
    } catch (err) {
      errors.push(`Legacy turn ${i}: ${err.message}`);
    }
  }

  return { turns, errors, partial: true };
}

function findGeminiScrollContainer() {
  const strategies = [
    () => document.querySelector('infinite-scroller[data-test-id="chat-history-container"]'),
    () => document.querySelector('#chat-history'),
    () => document.querySelector('.chat-history-scroll-container'),
    () => {
      const firstTurn = document.querySelector('div.conversation-container[id]');
      return firstTurn ? findScrollableAncestor(firstTurn) : null;
    },
  ];

  for (const strategy of strategies) {
    const result = strategy();
    if (result) return result;
  }
  return null;
}


// --- src/extractors/grok.js ---
// =============================================================================
// Chat Archive — Grok.com Extractor (Pass 0 + Direct Text Fallback)
// =============================================================================
// Architecture: Appendix A
// Turn container: div[id^="response-"] with scroll-margin-top
// Copy buttons: aria-label="Copy" on both roles (opacity-0 but clickable)
// Role signals: items-end (user) vs items-start (assistant) — 0.95
//               Button count: 2 (user) vs 8+ (assistant) — 0.95
//               Bubble styling: bg-surface-l1 (user) vs w-full (assistant) — 0.90

async function extractGrokConversation() {
  const startTime = Date.now();
  const turns = [];
  const errors = [];

  // 1. Find scroll container
  const scrollContainer = findGrokScrollContainer();
  if (!scrollContainer) {
    return { turns: [], errors: ['Scroll container not found'], partial: true };
  }

  // 2. Load all turns
  await scrollToLoadAll(scrollContainer, 'div[id^="response-"]', startTime);

  // 3. Get turn containers
  const turnContainers = document.querySelectorAll('div[id^="response-"]');
  console.log(`[Chat Archive] Grok: Found ${turnContainers.length} turn containers`);

  if (turnContainers.length === 0) {
    return { turns: [], errors: ['No turn containers found'], partial: true };
  }

  // 4. Clipboard test
  const hasClipboard = await testClipboardAccess();
  console.log(`[Chat Archive] Grok: Clipboard access: ${hasClipboard}`);

  // 5. Extract each turn
  for (let i = 0; i < turnContainers.length; i++) {
    if (Date.now() - startTime > SAFETY_LIMITS.MAX_EXTRACTION_TIME_MS) {
      errors.push(`Extraction timed out after ${SAFETY_LIMITS.MAX_EXTRACTION_TIME_MS}ms`);
      break;
    }
    if (turns.length >= SAFETY_LIMITS.MAX_TURNS) {
      errors.push(`Hit maximum turn limit (${SAFETY_LIMITS.MAX_TURNS})`);
      break;
    }

    const container = turnContainers[i];

    try {
      container.scrollIntoView({ behavior: 'instant', block: 'center' });
      await wait(150);

      const turn = await extractGrokTurn(container, hasClipboard);
      if (turn) turns.push(flagIfOversized(turn));
    } catch (err) {
      errors.push(`Error extracting turn ${i}: ${err.message}`);
      console.warn(`[Chat Archive] Grok: Error on turn ${i}:`, err);
    }
  }

  console.log(`[Chat Archive] Grok: Extracted ${turns.length} turns, ${errors.length} errors`);
  return { turns, errors, partial: errors.length > 0 };
}

async function extractGrokTurn(container, hasClipboard) {
  const turnId = container.id; // "response-{uuid}"

  // --- Role detection (3 independent signals) ---
  const role = detectGrokRole(container);
  if (!role) return null;

  // --- Pass 0: Clipboard ---
  let content = null;
  let extractionMethod = 'direct';

  if (hasClipboard) {
    try {
      const copyBtn = container.querySelector('button[aria-label="Copy"]')
        || findActionButton(container, ['Copy']);
      if (copyBtn) {
        const clipContent = await clickCopyAndRead(copyBtn);
        if (clipContent && clipContent.trim().length > 0) {
          content = clipContent;
          extractionMethod = 'clipboard';
        }
      }
    } catch (err) {
      console.warn(`[Chat Archive] Grok: Clipboard failed for ${turnId}:`, err);
    }
  }

  // --- Fallback: Direct text ---
  if (!content) {
    content = extractGrokDirectText(container, role);
    extractionMethod = 'direct';
  }

  if (!content || content.trim().length === 0) return null;

  return {
    role,
    content: content.trim(),
    turnId,
    extractionMethod,
    confidence: 0.95,
    classificationSource: 'structural',
  };
}

/**
 * Detect role using three independent signals.
 * Signal 1: Container alignment (items-end = user, items-start = assistant)
 * Signal 2: Button count (2 = user, 8+ = assistant)
 * Signal 3: Message bubble styling (bg-surface-l1 = user)
 */
function detectGrokRole(container) {
  const signals = { user: 0, assistant: 0 };

  // Signal 1: Alignment classes
  const classes = container.className || '';
  if (classes.includes('items-end')) signals.user += 2;
  else if (classes.includes('items-start')) signals.assistant += 2;

  // Also check child flex containers for alignment
  const flexChild = container.querySelector('[class*="items-end"]');
  const flexChildStart = container.querySelector('[class*="items-start"]');
  if (flexChild && !flexChildStart) signals.user += 1;
  if (flexChildStart && !flexChild) signals.assistant += 1;

  // Signal 2: Button count
  const buttons = container.querySelectorAll('button');
  if (buttons.length <= 3) signals.user += 2;
  else if (buttons.length >= 5) signals.assistant += 2;

  // Signal 3: Bubble styling
  const hasBubble = container.querySelector('[class*="bg-surface-l1"]');
  const hasFullWidth = container.querySelector('[class*="max-w-none"]');
  if (hasBubble) signals.user += 1;
  if (hasFullWidth) signals.assistant += 1;

  // Signal 4: Edit button (user only)
  const editBtn = container.querySelector('button[aria-label="Edit"]');
  if (editBtn) signals.user += 2;

  // Signal 5: Regenerate button (assistant only)
  const regenBtn = container.querySelector('button[aria-label="Regenerate"]');
  if (regenBtn) signals.assistant += 2;

  // Signal 6: Response time indicator (assistant only)
  const responseTime = container.querySelector('[class*="text-xs"]');
  if (responseTime && /\d+ms/.test(responseTime.textContent || '')) {
    signals.assistant += 1;
  }

  if (signals.user > signals.assistant) return 'user';
  if (signals.assistant > signals.user) return 'assistant';

  // Tie-breaker: default to alternation pattern (handled by heuristics pass)
  return null;
}

function extractGrokDirectText(container, role) {
  // Look for the message content area
  const markdown = container.querySelector('.message-bubble .response-content-markdown');
  if (markdown) return markdown.textContent?.trim() || '';

  // Broader: any .markdown inside the container
  const markdownAlt = container.querySelector('.markdown');
  if (markdownAlt) return markdownAlt.textContent?.trim() || '';

  // Broadest: main text content, excluding buttons
  const clone = container.cloneNode(true);
  // Remove action bars, follow-up suggestions
  clone.querySelectorAll('button, [class*="follow-up"], #last-reply-container').forEach(
    (el) => el.remove()
  );
  return clone.textContent?.trim() || '';
}

function findGrokScrollContainer() {
  const strategies = [
    () => document.querySelector('.w-full.h-full.overflow-y-auto.overflow-x-hidden'),
    () => document.querySelector('[class*="overflow-y-auto"][class*="scrollbar-gutter"]'),
    () => {
      const firstTurn = document.querySelector('div[id^="response-"]');
      return firstTurn ? findScrollableAncestor(firstTurn) : null;
    },
  ];

  for (const strategy of strategies) {
    const result = strategy();
    if (result) return result;
  }
  return null;
}


// --- src/extractors/grok-x.js ---
// =============================================================================
// Chat Archive — Grok x.com Extractor (Pass 0 + Direct Text Fallback)
// =============================================================================
// Architecture: Appendix B
// CRITICAL: x.com/i/grok has ZERO common selectors with grok.com
// Framework: React Native Web (hashed classes: css-175oi2r, r-*)
// Copy button: aria-label="Copy text" on ASSISTANT only
// User turns: NO copy button — must use direct text extraction
// Role signals: follow_ups_list presence (assistant), button presence

async function extractGrokXConversation() {
  const startTime = Date.now();
  const turns = [];
  const errors = [];

  // 1. Find scroll container — no reliable selector, walk up from content
  const scrollContainer = findGrokXScrollContainer();
  if (!scrollContainer) {
    return { turns: [], errors: ['Scroll container not found'], partial: true };
  }

  // 2. Scroll to load all content
  // x.com Grok doesn't have clean turn containers — we need to identify turn boundaries
  await scrollToLoadAllGrokX(scrollContainer, startTime);

  // 3. Identify turn blocks
  // x.com Grok uses flat sibling divs without per-turn IDs.
  // Strategy: find all "Copy text" buttons (assistant markers) and work outward
  const turnBlocks = identifyGrokXTurnBlocks();
  console.log(`[Chat Archive] Grok-X: Identified ${turnBlocks.length} turn blocks`);

  if (turnBlocks.length === 0) {
    return { turns: [], errors: ['No turn blocks identified'], partial: true };
  }

  // 4. Clipboard test
  const hasClipboard = await testClipboardAccess();
  console.log(`[Chat Archive] Grok-X: Clipboard access: ${hasClipboard}`);

  // 5. Extract each turn
  for (let i = 0; i < turnBlocks.length; i++) {
    if (Date.now() - startTime > SAFETY_LIMITS.MAX_EXTRACTION_TIME_MS) {
      errors.push(`Extraction timed out`);
      break;
    }
    if (turns.length >= SAFETY_LIMITS.MAX_TURNS) {
      errors.push(`Hit maximum turn limit`);
      break;
    }

    const block = turnBlocks[i];

    try {
      block.element.scrollIntoView({ behavior: 'instant', block: 'center' });
      await wait(150);

      const turn = await extractGrokXTurn(block, hasClipboard);
      if (turn) turns.push(flagIfOversized(turn));
    } catch (err) {
      errors.push(`Error on block ${i}: ${err.message}`);
      console.warn(`[Chat Archive] Grok-X: Error on block ${i}:`, err);
    }
  }

  console.log(`[Chat Archive] Grok-X: Extracted ${turns.length} turns, ${errors.length} errors`);
  return { turns, errors, partial: errors.length > 0 };
}

/**
 * Identify turn blocks in x.com/i/grok's flat DOM structure.
 * Strategy: 
 *   - Assistant turns have "Copy text" buttons and/or follow_ups_list
 *   - User turns are the blocks between assistant turns that have no action buttons
 */
function identifyGrokXTurnBlocks() {
  const blocks = [];

  // Find all major content containers in the chat area
  // x.com uses deeply nested divs with hashed classes
  // Best approach: find all "Copy text" buttons and their ancestor containers
  const copyButtons = document.querySelectorAll('button[aria-label="Copy text"]');
  const followUps = document.querySelectorAll('[data-testid="follow_ups_list"]');

  // Build a set of assistant container elements
  const assistantContainers = new Set();
  const assistantElements = [];

  for (const btn of copyButtons) {
    // Walk up to find the turn-level container
    // Typically: button → action bar → content block → turn container
    let container = btn.parentElement;
    for (let depth = 0; depth < 8 && container; depth++) {
      // Heuristic: turn containers tend to be direct children of the main scroll area
      if (container.parentElement &&
          container.parentElement.children.length > 2 &&
          container.previousElementSibling) {
        break;
      }
      container = container.parentElement;
    }
    if (container && !assistantContainers.has(container)) {
      assistantContainers.add(container);
      assistantElements.push({ element: container, role: 'assistant', copyButton: btn });
    }
  }

  // If we found assistant containers, their siblings before each are likely user turns
  if (assistantElements.length > 0) {
    // Get the parent that holds all turn siblings
    const parent = assistantElements[0].element.parentElement;
    if (!parent) return assistantElements;

    const children = Array.from(parent.children);
    let lastAssistantIdx = -1;

    for (let i = 0; i < children.length; i++) {
      const child = children[i];

      if (assistantContainers.has(child)) {
        // Everything between lastAssistantIdx and this is user content
        // But often there's just one user block before each assistant
        if (i > 0 && i - 1 > lastAssistantIdx) {
          // Check each block between last assistant and this assistant
          for (let j = lastAssistantIdx + 1; j < i; j++) {
            const candidate = children[j];
            const text = candidate.textContent?.trim() || '';
            // Filter out empty blocks, navigation, follow-ups
            if (text.length > 0 &&
                !candidate.querySelector('[data-testid="follow_ups_list"]') &&
                !candidate.querySelector('button[aria-label="Copy text"]') &&
                !candidate.querySelector('textarea')) {
              blocks.push({ element: candidate, role: 'user', copyButton: null });
            }
          }
        }
        blocks.push(assistantContainers.has(child)
          ? assistantElements.find((a) => a.element === child) || { element: child, role: 'assistant', copyButton: null }
          : { element: child, role: 'assistant', copyButton: null });
        lastAssistantIdx = i;
      }
    }

    return blocks;
  }

  // Fallback: no assistant markers found — try raw text extraction with heuristics
  return [];
}

async function extractGrokXTurn(block, hasClipboard) {
  const { element, role, copyButton } = block;

  let content = null;
  let extractionMethod = 'direct';

  // --- Pass 0: Clipboard (assistant only on x.com) ---
  if (role === 'assistant' && hasClipboard && copyButton) {
    try {
      const clipContent = await clickCopyAndRead(copyButton);
      if (clipContent && clipContent.trim().length > 0) {
        content = clipContent;
        extractionMethod = 'clipboard';
      }
    } catch (err) {
      console.warn(`[Chat Archive] Grok-X: Assistant clipboard failed:`, err);
    }
  }

  // --- Direct text extraction ---
  if (!content) {
    content = extractGrokXDirectText(element, role);
    extractionMethod = 'direct';
  }

  if (!content || content.trim().length === 0) return null;

  return {
    role,
    content: content.trim(),
    extractionMethod,
    confidence: role === 'assistant' ? 0.95 : 0.80,
    classificationSource: 'structural',
  };
}

function extractGrokXDirectText(element, role) {
  // Clone and strip non-content elements
  const clone = element.cloneNode(true);

  // Remove follow-up suggestions, buttons, textareas
  clone.querySelectorAll(
    '[data-testid="follow_ups_list"], button, textarea, svg, [role="img"]'
  ).forEach((el) => el.remove());

  // For user turns, look for the specific text container class
  if (role === 'user') {
    // x.com Grok user text containers have class r-1kt6imw
    const userText = element.querySelector('[class*="r-1kt6imw"]');
    if (userText) return userText.textContent?.trim() || '';
  }

  // For assistant turns, look for formatted content
  if (role === 'assistant') {
    const assistantText = element.querySelector('[class*="r-rjixqe"]');
    if (assistantText) return assistantText.textContent?.trim() || '';
  }

  return clone.textContent?.trim() || '';
}

async function scrollToLoadAllGrokX(scrollContainer, startTime) {
  let previousHeight = 0;
  let stableIterations = 0;
  let scrollIterations = 0;

  scrollContainer.scrollTop = 0;
  await wait(500);

  while (
    stableIterations < SAFETY_LIMITS.SCROLL_STABILITY_THRESHOLD &&
    scrollIterations < SAFETY_LIMITS.MAX_SCROLL_ITERATIONS
  ) {
    if (startTime && Date.now() - startTime > SAFETY_LIMITS.MAX_EXTRACTION_TIME_MS) break;

    const currentHeight = scrollContainer.scrollHeight;
    if (currentHeight === previousHeight) {
      stableIterations++;
    } else {
      stableIterations = 0;
      previousHeight = currentHeight;
    }

    scrollContainer.scrollBy(0, scrollContainer.clientHeight * 0.8);
    await wait(SAFETY_LIMITS.SCROLL_STEP_DELAY_MS);
    scrollIterations++;
  }

  scrollContainer.scrollTop = 0;
  await wait(200);
}

function findGrokXScrollContainer() {
  const strategies = [
    // x.com's Grok chat area
    () => {
      const grokSection = document.querySelector('[data-testid="GrokChat"]');
      if (grokSection) {
        const scrollable = grokSection.querySelector('[class*="overflow-y-auto"]')
          || grokSection.querySelector('[style*="overflow"]');
        if (scrollable) return scrollable;
        return findScrollableAncestor(grokSection);
      }
      return null;
    },
    // Generic: find scrollable ancestor of first copy button
    () => {
      const firstBtn = document.querySelector('button[aria-label="Copy text"]');
      return firstBtn ? findScrollableAncestor(firstBtn) : null;
    },
    // Broadest: main scrollable area on x.com
    () => document.querySelector('main [class*="overflow"][class*="auto"]'),
  ];

  for (const strategy of strategies) {
    const result = strategy();
    if (result) return result;
  }
  return null;
}


// --- src/extractors/perplexity.js ---
// =============================================================================
// Chat Archive — Perplexity.ai Extractor (Pass 0 + Direct Text Fallback)
// =============================================================================
// Architecture: Similar to Greasy Fork Perplexity Chat Exporter
// User query: button[data-testid="copy-query-button"] or button[aria-label="Copy Query"]
// Assistant: button[aria-label="Copy"] (with SVG, excludes pre/code blocks)
// Content: .whitespace-pre-line.text-pretty.break-words (user), .prose (assistant)
// Thread container: .max-w-threadContentWidth, [class*="threadContentWidth"], or main

async function extractPerplexityConversation(options = {}) {
  const startTime = Date.now();
  const turns = [];
  const errors = [];

  const scrollContainer = findPerplexityScrollContainer();
  console.log('[Chat Archive] Perplexity: Scroll container found:', scrollContainer?.tagName, scrollContainer?.className);
  if (!scrollContainer) {
    return { turns: [], errors: ['Scroll container not found'], partial: true };
  }

  // Visual indicator: flash the scroll container border
  const originalBorder = scrollContainer.style.border;
  scrollContainer.style.border = '3px solid red';
  await wait(500);
  scrollContainer.style.border = originalBorder;

  // Always scroll to load all content (Perplexity lazy-loads)
  console.log('[Chat Archive] Perplexity: Starting scroll-to-load...');
  const scrollCount = await scrollToLoadAll(
    scrollContainer,
    'button[data-testid="copy-query-button"], button[aria-label="Copy Query"], .prose.text-pretty',
    startTime
  );
  console.log('[Chat Archive] Perplexity: Scroll complete, performed', scrollCount, 'scrolls');

  // Skip clipboard for Perplexity - it's too slow for project exports (can exceed 30s message timeout)
  // Use direct text extraction only for speed
  console.log(`[Chat Archive] Perplexity: Using direct text extraction (skipping clipboard for speed)`);

  const queryButtons = Array.from(document.querySelectorAll('button[data-testid="copy-query-button"], button[aria-label="Copy Query"]'))
    .filter((btn) => !btn.closest('pre, code'));
  const responseButtons = Array.from(document.querySelectorAll('button[aria-label="Copy"]'))
    .filter((btn) => {
      if (btn.closest('pre, code')) return false;
      if (btn.querySelector('svg')) return true;
      return false;
    });

  const allItems = [
    ...queryButtons.map((btn) => ({ btn, role: 'user' })),
    ...responseButtons.map((btn) => ({ btn, role: 'assistant' })),
  ].sort((a, b) => a.btn.getBoundingClientRect().top - b.btn.getBoundingClientRect().top);

  const processedHashes = new Set();

  for (const { btn, role } of allItems) {
    if (Date.now() - startTime > SAFETY_LIMITS.MAX_EXTRACTION_TIME_MS) {
      errors.push(`Extraction timed out after ${SAFETY_LIMITS.MAX_EXTRACTION_TIME_MS}ms`);
      break;
    }
    if (turns.length >= SAFETY_LIMITS.MAX_TURNS) {
      errors.push(`Hit maximum turn limit (${SAFETY_LIMITS.MAX_TURNS})`);
      break;
    }

    try {
      // Direct text extraction only (no clipboard, no scrollIntoView, no waits)
      const content = role === 'user'
        ? extractPerplexityUserDirectText(btn)
        : extractPerplexityAssistantDirectText(btn);

      if (!content || content.trim().length === 0) continue;

      const hash = content.substring(0, 150) + content.length + '|' + role;
      if (processedHashes.has(hash)) continue;
      processedHashes.add(hash);

      turns.push(flagIfOversized({
        role,
        content: content.trim(),
        extractionMethod: 'direct',
        confidence: 0.95,
        classificationSource: 'structural',
      }));
    } catch (err) {
      errors.push(`Error extracting ${role} turn: ${err.message}`);
      console.warn(`[Chat Archive] Perplexity: Error:`, err);
    }
  }

  console.log(`[Chat Archive] Perplexity: Extracted ${turns.length} turns, ${errors.length} errors`);
  return { turns, errors, partial: errors.length > 0 };
}

function findPerplexityUserRoot(btn) {
  let node = btn;
  for (let d = 0; d < 12 && node && node !== document.body; d++) {
    if (node.querySelector?.('.whitespace-pre-line.text-pretty.break-words, span[data-lexical-text="true"], span.select-text')) {
      return node;
    }
    node = node.parentElement;
  }
  return btn.parentElement;
}

function findPerplexityAssistantRoot(btn) {
  let node = btn;
  for (let d = 0; d < 12 && node && node !== document.body; d++) {
    if (node.querySelector?.('.prose.text-pretty, [data-testid="answer"], [data-testid="assistant"]')) {
      return node;
    }
    node = node.parentElement;
  }
  return btn.parentElement;
}

function extractPerplexityUserDirectText(btn) {
  const root = findPerplexityUserRoot(btn);
  const textEl = root?.querySelector('.whitespace-pre-line.text-pretty.break-words, span[data-lexical-text="true"], span.select-text');
  if (textEl) return textEl.textContent?.trim() || '';
  return root?.textContent?.trim() || '';
}

function extractPerplexityAssistantDirectText(btn) {
  const root = findPerplexityAssistantRoot(btn);
  const prose = root?.querySelector('.prose.text-pretty.dark\\:prose-invert, .prose, [data-testid="answer"], [data-testid="assistant"]');
  if (prose) return prose.textContent?.trim() || '';
  const clone = root?.cloneNode(true);
  if (clone) {
    clone.querySelectorAll?.('button, pre, code').forEach((el) => el.remove());
    return clone.textContent?.trim() || '';
  }
  return root?.textContent?.trim() || '';
}

function findPerplexityScrollContainer() {
  const strategies = [
    () => document.querySelector('.max-w-threadContentWidth, [class*="threadContentWidth"]'),
    () => document.querySelector('main'),
    () => {
      const first = document.querySelector('button[data-testid="copy-query-button"], .prose');
      return first ? findScrollableAncestor(first) : null;
    },
    () => document.scrollingElement || document.documentElement,
  ];

  for (const strategy of strategies) {
    const result = strategy();
    if (result) return result;
  }
  return null;
}


// --- src/heuristics/pass1.js ---
// =============================================================================
// Chat Archive — Pass 1: Structural Heuristics
// =============================================================================
// Classifies turns using rule-based pattern detection when Pass 0
// (button extraction) didn't produce confident role assignments.
//
// Heuristic rules are ordered by confidence:
//   H1: Explicit role attributes (0.95)
//   H2: Alternating binary pattern (0.85)
//   H3: Asymmetric text length (0.70)
//   H4: Background color differentiation (0.75)
//   H5: Alignment pattern (0.80)
//   H6: Avatar/icon presence (0.70)
//   H7: Code block density (0.60)
//
// Combined confidence = weighted average of all firing rules.
// Threshold: 0.75 — accept classification if combined >= 0.75

const HEURISTIC_THRESHOLD = 0.75;

/**
 * Run heuristic classification on an array of extracted turns.
 * Turns that already have confidence >= threshold are left untouched.
 * Turns with lower confidence (or no role) get heuristic analysis.
 *
 * @param {Array} turns - Array of turn objects from extractors
 * @returns {Array} Same array with updated role/confidence/classificationSource
 */
function applyHeuristics(turns) {
  if (turns.length === 0) return turns;

  // Collect turns that need classification
  const needsClassification = [];
  for (let i = 0; i < turns.length; i++) {
    if (!turns[i].role || (turns[i].confidence || 0) < HEURISTIC_THRESHOLD) {
      needsClassification.push(i);
    }
  }

  if (needsClassification.length === 0) {
    console.log('[Chat Archive] Heuristics: All turns already classified at high confidence');
    return turns;
  }

  console.log(`[Chat Archive] Heuristics: ${needsClassification.length} turns need classification`);

  // Run each heuristic rule across the full conversation for context
  const results = turns.map((turn, index) => ({
    index,
    scores: { user: 0, assistant: 0 },
    rulesApplied: [],
    totalWeight: 0,
  }));

  // H1: Explicit role attributes (already handled by extractors, but double-check)
  applyH1ExplicitRoles(turns, results);

  // H2: Alternating binary pattern
  applyH2AlternatingPattern(turns, results);

  // H3: Asymmetric text length
  applyH3TextLength(turns, results);

  // H4: Background color / styling differentiation (requires DOM — use cached data)
  // (Skipped in post-extraction heuristics — this runs on already-extracted text)

  // H5: Content-based alignment signals (encoded in content or metadata)
  applyH5ContentSignals(turns, results);

  // H7: Code block density
  applyH7CodeBlocks(turns, results);

  // Apply results to turns that need classification
  for (const idx of needsClassification) {
    const result = results[idx];
    if (result.totalWeight === 0) continue;

    const userScore = result.scores.user / result.totalWeight;
    const assistantScore = result.scores.assistant / result.totalWeight;
    const confidence = Math.max(userScore, assistantScore);
    const role = userScore > assistantScore ? 'user' : 'assistant';

    if (confidence >= HEURISTIC_THRESHOLD) {
      turns[idx].role = role;
      turns[idx].confidence = parseFloat(confidence.toFixed(3));
      turns[idx].classificationSource = 'heuristic';
      turns[idx].heuristicRules = result.rulesApplied;
    } else {
      // Mark as uncertain for User Resolution UI
      turns[idx].confidence = parseFloat(confidence.toFixed(3));
      turns[idx].classificationSource = 'heuristic-uncertain';
      turns[idx].heuristicRules = result.rulesApplied;
      turns[idx].needsUserResolution = true;
    }
  }

  const resolved = needsClassification.filter(
    (i) => turns[i].confidence >= HEURISTIC_THRESHOLD && turns[i].role
  ).length;
  console.log(`[Chat Archive] Heuristics: Resolved ${resolved}/${needsClassification.length} turns`);

  return turns;
}

// --- Individual Heuristic Rules ---

/**
 * H1: Explicit role attributes in content or metadata.
 * Confidence: 0.95. Weight: 3.
 */
function applyH1ExplicitRoles(turns, results) {
  for (let i = 0; i < turns.length; i++) {
    const turn = turns[i];

    // Already classified with high confidence from extractor
    if (turn.role && (turn.confidence || 0) >= 0.90) {
      const target = turn.role === 'user' ? 'user' : 'assistant';
      results[i].scores[target] += 3 * 0.95;
      results[i].totalWeight += 3;
      results[i].rulesApplied.push('H1-explicit');
    }
  }
}

/**
 * H2: Alternating binary pattern.
 * If we have high-confidence turns at known positions, the turns between them
 * should alternate. Confidence: 0.85. Weight: 2.
 */
function applyH2AlternatingPattern(turns, results) {
  // Find anchor points (turns with high confidence)
  const anchors = [];
  for (let i = 0; i < turns.length; i++) {
    if (turns[i].role && (turns[i].confidence || 0) >= 0.90) {
      anchors.push({ index: i, role: turns[i].role });
    }
  }

  if (anchors.length === 0) {
    // No anchors — assume first turn is user (most conversations start this way)
    for (let i = 0; i < turns.length; i++) {
      const expectedRole = i % 2 === 0 ? 'user' : 'assistant';
      results[i].scores[expectedRole] += 2 * 0.85;
      results[i].totalWeight += 2;
      results[i].rulesApplied.push('H2-alternation-noanchor');
    }
    return;
  }

  // Propagate from anchors
  for (let i = 0; i < turns.length; i++) {
    // Find nearest anchor
    let nearest = anchors[0];
    let minDist = Math.abs(i - nearest.index);
    for (const anchor of anchors) {
      const dist = Math.abs(i - anchor.index);
      if (dist < minDist) {
        minDist = dist;
        nearest = anchor;
      }
    }

    // Expected role based on distance from anchor (alternating)
    const offset = i - nearest.index;
    const anchorIsUser = nearest.role === 'user';
    const expectedRole = (offset % 2 === 0) === anchorIsUser ? 'user' : 'assistant';

    // Confidence decreases with distance from anchor
    const distancePenalty = Math.max(0, 1 - minDist * 0.05);
    const weight = 2 * distancePenalty;

    results[i].scores[expectedRole] += weight * 0.85;
    results[i].totalWeight += weight;
    results[i].rulesApplied.push('H2-alternation');
  }
}

/**
 * H3: Asymmetric text length.
 * User messages tend to be shorter than assistant responses.
 * Confidence: 0.70. Weight: 1.
 */
function applyH3TextLength(turns, results) {
  if (turns.length < 2) return;

  // Calculate median text length
  const lengths = turns.map((t) => (t.content || '').length);
  const sorted = [...lengths].sort((a, b) => a - b);
  const median = sorted[Math.floor(sorted.length / 2)];

  if (median === 0) return;

  for (let i = 0; i < turns.length; i++) {
    const len = lengths[i];
    const ratio = len / median;

    // Short messages are more likely user turns
    if (ratio < 0.5) {
      results[i].scores.user += 1 * 0.70;
      results[i].totalWeight += 1;
      results[i].rulesApplied.push('H3-short');
    } else if (ratio > 2.0) {
      results[i].scores.assistant += 1 * 0.70;
      results[i].totalWeight += 1;
      results[i].rulesApplied.push('H3-long');
    }
    // Near-median: no signal
  }
}

/**
 * H5: Content-based signals.
 * Assistant messages tend to contain markdown formatting, lists, code blocks.
 * User messages tend to be questions or short directives.
 * Confidence: 0.65. Weight: 1.
 */
function applyH5ContentSignals(turns, results) {
  for (let i = 0; i < turns.length; i++) {
    const text = turns[i].content || '';

    // Assistant signals
    let assistantSignals = 0;
    if (text.includes('```')) assistantSignals += 2;          // Code fences
    if (/^\s*[-*]\s/m.test(text)) assistantSignals += 1;     // Bullet lists
    if (/^\s*\d+\.\s/m.test(text)) assistantSignals += 1;   // Numbered lists
    if (/^#{1,3}\s/m.test(text)) assistantSignals += 1;      // Markdown headings
    if (text.length > 500) assistantSignals += 1;             // Long content

    // User signals
    let userSignals = 0;
    if (text.endsWith('?')) userSignals += 2;                 // Questions
    if (text.length < 100) userSignals += 1;                  // Short
    if (/^(can you|please|help|what|how|why|when|where|who|is|are|do|does)/i.test(text)) {
      userSignals += 1;                                       // Question starters
    }

    if (assistantSignals > userSignals) {
      results[i].scores.assistant += 1 * 0.65;
      results[i].totalWeight += 1;
      results[i].rulesApplied.push('H5-content-assistant');
    } else if (userSignals > assistantSignals) {
      results[i].scores.user += 1 * 0.65;
      results[i].totalWeight += 1;
      results[i].rulesApplied.push('H5-content-user');
    }
  }
}

/**
 * H7: Code block density.
 * Messages with code blocks are almost always assistant turns.
 * Confidence: 0.60 (lower because users sometimes paste code too).
 * Weight: 1.
 */
function applyH7CodeBlocks(turns, results) {
  for (let i = 0; i < turns.length; i++) {
    const text = turns[i].content || '';
    const codeBlocks = (text.match(/```/g) || []).length / 2;

    if (codeBlocks >= 1) {
      results[i].scores.assistant += 1 * 0.60;
      results[i].totalWeight += 1;
      results[i].rulesApplied.push('H7-codeblocks');
    }
  }
}

/**
 * Post-heuristic integrity: verify the overall conversation makes sense.
 * Returns an array of warning strings.
 */
function heuristicIntegrityCheck(turns) {
  const warnings = [];

  // Check that we have at least some role diversity
  const roles = new Set(turns.map((t) => t.role).filter(Boolean));
  if (roles.size < 2 && turns.length > 1) {
    warnings.push('All turns classified as the same role — heuristics may have failed');
  }

  // Check for runs of same role > 3
  let maxRun = 0;
  let currentRun = 1;
  for (let i = 1; i < turns.length; i++) {
    if (turns[i].role === turns[i - 1].role) {
      currentRun++;
      maxRun = Math.max(maxRun, currentRun);
    } else {
      currentRun = 1;
    }
  }
  if (maxRun > 3) {
    warnings.push(`${maxRun} consecutive turns with the same role detected`);
  }

  // Count uncertain turns
  const uncertain = turns.filter((t) => t.needsUserResolution).length;
  if (uncertain > 0) {
    warnings.push(`${uncertain} turn(s) could not be confidently classified`);
  }

  return warnings;
}


// --- src/utils/serializer.js ---
// =============================================================================
// Chat Archive — Serializer (JSON + Markdown)
// =============================================================================
// Transforms extracted turns into durable export formats.
// JSON is the canonical format. Markdown is the human-readable format.
// Both are addressable artifacts — they have destinations beyond the export.

/**
 * Serialize extracted turns into the canonical JSON export format.
 */
function serializeToJSON(extraction, platform) {
  const integrityWarnings = runIntegrityChecks(extraction.turns);

  const exportData = {
    schema_version: SCHEMA_VERSION,
    export_metadata: {
      source_platform: platformToDisplayName(platform),
      source_url: window.location.href,
      export_timestamp: new Date().toISOString(),
      extension_version: EXTENSION_VERSION,
      total_turns: extraction.turns.length,
      flagged_turns: extraction.turns.filter((t) => t.flagged).length,
      partial_export: extraction.partial || false,
      extraction_errors: extraction.errors || [],
      integrity_warnings: integrityWarnings,
    },
    conversation: extraction.turns.map((turn, index) => {
      const entry = {
        turn: index + 1,
        role: turn.role || 'unknown',
        content: turn.content,
        classification_confidence: turn.confidence || null,
        classification_source: turn.classificationSource || 'unknown',
      };

      // Optional fields
      if (turn.timestamp) entry.timestamp = turn.timestamp;
      if (turn.flagged) {
        entry.flagged = true;
        entry.flag_reason = turn.flagReason;
      }
      if (turn.extractionMethod) entry.extraction_method = turn.extractionMethod;
      if (turn.turnId) entry.turn_id = turn.turnId;
      if (turn.modelSlug) entry.model = turn.modelSlug;
      if (turn.needsUserResolution) entry.needs_user_resolution = true;

      return entry;
    }),
  };

  return {
    json: JSON.stringify(exportData, null, 2),
    metadata: exportData.export_metadata,
    integrityWarnings,
  };
}

/**
 * Serialize extracted turns into Markdown format.
 */
function serializeToMarkdown(extraction, platform) {
  const integrityWarnings = runIntegrityChecks(extraction.turns);

  const platformName = platformToDisplayName(platform);
  const timestamp = new Date().toISOString().replace('T', ' ').slice(0, 19) + ' UTC';
  const sourceUrl = window.location.href;

  const lines = [];

  // --- Header ---
  lines.push(`# Chat Export — ${platformName}`);
  lines.push(`**Exported:** ${timestamp}  `);
  lines.push(`**Source:** ${sourceUrl}  `);
  lines.push(`**Turns:** ${extraction.turns.length}`);

  if (extraction.partial) {
    lines.push(`**Status:** Partial export (${extraction.errors.length} errors)`);
  }

  lines.push('');
  lines.push('---');
  lines.push('');

  // --- Turns ---
  for (let i = 0; i < extraction.turns.length; i++) {
    const turn = extraction.turns[i];
    const role = turn.role || 'Unknown';
    const roleLabel = role.charAt(0).toUpperCase() + role.slice(1);

    lines.push(`## ${roleLabel}`);

    if (turn.timestamp) {
      lines.push(`*${turn.timestamp}*`);
      lines.push('');
    }

    // Content: preserve as-is (clipboard extraction gives us markdown already)
    lines.push(turn.content || '*(empty)*');

    if (turn.flagged) {
      lines.push('');
      lines.push(`> ⚠️ ${turn.flagReason || 'Flagged'}`);
    }

    if (turn.needsUserResolution) {
      lines.push('');
      lines.push('> ⚠️ Role classification uncertain — may need manual correction');
    }

    lines.push('');
    lines.push('---');
    lines.push('');
  }

  // --- Footer ---
  if (integrityWarnings.length > 0) {
    lines.push('## Export Notes');
    lines.push('');
    for (const warning of integrityWarnings) {
      lines.push(`- ${warning}`);
    }
    lines.push('');
  }

  lines.push(`*Exported by Chat Archive v${EXTENSION_VERSION}*`);

  return {
    markdown: lines.join('\n'),
    metadata: {
      source_platform: platformName,
      source_url: sourceUrl,
      export_timestamp: new Date().toISOString(),
      extension_version: EXTENSION_VERSION,
      total_turns: extraction.turns.length,
      flagged_turns: extraction.turns.filter((t) => t.flagged).length,
      partial_export: extraction.partial || false,
    },
    integrityWarnings,
  };
}

/**
 * Run integrity checks on extracted turns before serialization.
 */
function runIntegrityChecks(turns) {
  const warnings = [];

  if (turns.length === 0) {
    warnings.push('No turns extracted');
    return warnings;
  }

  // Check 1: Turn alternation pattern
  let alternationViolations = 0;
  for (let i = 1; i < turns.length; i++) {
    if (turns[i].role === turns[i - 1].role) {
      alternationViolations++;
    }
  }
  if (alternationViolations > 0) {
    warnings.push(
      `${alternationViolations} consecutive same-role turn(s) detected. ` +
      'This may indicate missed turns or system messages.'
    );
  }

  // Check 2: Consecutive duplicate content
  for (let i = 1; i < turns.length; i++) {
    if (turns[i].content === turns[i - 1].content && turns[i].content.length > 0) {
      warnings.push(`Duplicate content detected between turns ${i} and ${i + 1}`);
    }
  }

  // Check 3: Suspiciously large turns
  const largeTurns = turns.filter((t) => t.content.length > SAFETY_LIMITS.MAX_SINGLE_TURN_SIZE);
  if (largeTurns.length > 0) {
    warnings.push(`${largeTurns.length} turn(s) exceed 100KB`);
  }

  // Check 4: Empty turns
  const emptyTurns = turns.filter((t) => !t.content || t.content.trim().length === 0);
  if (emptyTurns.length > 0) {
    warnings.push(`${emptyTurns.length} empty turn(s) detected`);
  }

  // Check 5: Unresolved roles
  const unknownRoles = turns.filter((t) => !t.role || t.role === 'unknown');
  if (unknownRoles.length > 0) {
    warnings.push(`${unknownRoles.length} turn(s) with unknown roles`);
  }

  return warnings;
}


// --- src/utils/filewriter.js ---
// =============================================================================
// Chat Archive — File Writer
// =============================================================================
// Writes serialized output to user's device via Chrome downloads API.
// Phase 2: JSON + Markdown.
// slugForExport and buildExportFilename are loaded from filename-builder.js (listed first in manifest content_scripts).

/**
 * Download content as a file using the Chrome downloads API via background.js.
 */
function downloadViaBackground(content, filename, mimeType) {
  return new Promise((resolve, reject) => {
    chrome.runtime.sendMessage(
      {
        action: 'download',
        content,
        filename,
        mimeType,
      },
      (response) => {
        if (chrome.runtime.lastError) {
          reject(new Error(chrome.runtime.lastError.message));
        } else if (response && response.success) {
          resolve(response);
        } else {
          reject(new Error(response?.error || 'Download failed'));
        }
      }
    );
  });
}

/**
 * Fallback: Download via Blob URL and <a> click.
 */
function downloadViaBlob(content, filename, mimeType) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Download a file. Background uses a data URL for smaller payloads so it works after worker sleep.
 */
async function downloadFile(content, filename, mimeType) {
  try {
    await downloadViaBackground(content, filename, mimeType);
    return;
  } catch (err) {
    console.warn('[Chat Archive] Background download failed, trying in-page blob:', err.message);
    downloadViaBlob(content, filename, mimeType);
  }
}


// --- src/content.js ---
// =============================================================================
// Chat Archive — Content Script (Orchestrator)
// =============================================================================
// Injected into AI chat platform pages. Orchestrates:
//   Pass 0: Platform-specific button extraction (clipboard)
//   Pass 1: Structural heuristics (fallback for uncertain turns)
//   Serialization: JSON + Markdown
//   Download: via Chrome API or blob fallback

// =============================================================================
// Project & Chat Discovery (ChatGPT)
// =============================================================================

function discoverChatGPTProjects() {
  const projects = [];
  
  const sidebar = document.querySelector('aside, nav[aria-label*="sidebar" i], div[class*="sidebar"]');
  if (!sidebar) {
    return { error: 'Sidebar not found', projects: [] };
  }

  const projectElements = sidebar.querySelectorAll('a[href*="/p/"], a[href*="/project/"]');
  
  for (const elem of projectElements) {
    const href = elem.getAttribute('href');
    if (!href) continue;
    
    const match = href.match(/\/p\/([^\/]+)/);
    if (!match) continue;
    
    const projectId = match[1];
    const projectName = elem.textContent?.trim() || `Project ${projectId}`;
    
    projects.push({
      id: projectId,
      name: projectName,
      url: href.startsWith('http') ? href : `https://chatgpt.com${href}`,
    });
  }
  
  return { projects };
}

function discoverChatGPTChatsInCurrentProject() {
  const chats = [];
  const seenIds = new Set();

  function getChatTitleFromLink(link) {
    const aria = link.getAttribute('aria-label')?.trim();
    if (aria) return aria;
    const titleEl = link.querySelector('[class*="title" i], [class*="heading" i], strong, b');
    if (titleEl) {
      const t = titleEl.textContent?.trim();
      if (t) return t;
    }
    const full = link.textContent?.trim() || '';
    const firstLine = full.split(/\n/)[0]?.trim();
    if (firstLine) return firstLine;
    return full || null;
  }

  function addChat(link) {
    const href = link.getAttribute('href');
    if (!href) return;
    const match = href.match(/\/c\/([^\/\?]+)/);
    if (!match) return;
    const chatId = match[1];
    if (seenIds.has(chatId)) return;
    seenIds.add(chatId);
    const title = getChatTitleFromLink(link) || link.textContent?.trim() || `Chat ${chatId}`;
    chats.push({
      id: chatId,
      title,
      url: href.startsWith('http') ? href : `https://chatgpt.com${href}`,
    });
  }

  function isInsideLeftNav(link) {
    for (const root of leftNavRoots) {
      if (root.contains(link)) return true;
    }
    return false;
  }

  const isProjectPage = /\/g\/[^/]+\/project/.test(window.location.href) || /\/p\/[^/]+/.test(window.location.href);

  // All possible left-nav roots: sidebars, asides, navs (projects list + chats below are often in these).
  const leftNavRoots = [
    ...document.querySelectorAll('aside'),
    ...document.querySelectorAll('nav'),
    ...document.querySelectorAll('[class*="sidebar" i]'),
    ...document.querySelectorAll('[data-testid*="sidebar" i]'),
    ...document.querySelectorAll('[data-testid*="side-bar" i]'),
    ...document.querySelectorAll('[aria-label*="sidebar" i]'),
  ].filter((el) => el && el.isConnected);

  if (isProjectPage) {
    // Project is selected: only list chats in the main content. Exclude anything in left nav (all asides/navs/sidebars).
    const allChatLinks = document.querySelectorAll('a[href*="/c/"]');
    for (const link of allChatLinks) {
      if (isInsideLeftNav(link)) continue;
      addChat(link);
    }
  } else {
    // No project selected: list chats from the left nav only (all sidebar/aside/nav containers).
    for (const root of leftNavRoots) {
      root.querySelectorAll('a[href*="/c/"]').forEach(addChat);
    }
  }

  return { chats };
}

/**
 * Get the current ChatGPT project ID (if any) from the URL.
 * Returns { id } only — name is user-supplied, not inferred.
 */
function getCurrentChatGPTProject() {
  const url = window.location.href;
  const pMatch = url.match(/\/p\/([^\/]+)/);
  if (pMatch) return { id: pMatch[1], name: null };
  const gMatch = url.match(/\/g\/([^\/]+)\/project/);
  if (gMatch) return { id: gMatch[1], name: null };
  return null;
}

// ============================================================================
// Claude Projects Discovery
// ============================================================================

function discoverClaudeProjects() {
  const projects = [];
  
  // Look for project cards on claude.ai/projects page
  // Projects are linked with href="/project/[uuid]"
  const projectLinks = document.querySelectorAll('a[href*="/project/"]');
  
  for (const link of projectLinks) {
    const href = link.getAttribute('href');
    if (!href || !href.includes('/project/')) continue;
    
    // Extract project ID from URL: /project/019ca130-e1a3-7744-b81a-c59ac3b2a31f
    const match = href.match(/\/project\/([a-f0-9-]+)/);
    if (!match) continue;
    
    const projectId = match[1];
    
    // Find project name - look for .font-base-bold or text content
    const nameEl = link.querySelector('.font-base-bold, [class*="truncate"]');
    const projectName = nameEl?.textContent?.trim() || link.textContent?.trim() || `Project ${projectId}`;
    
    projects.push({
      id: projectId,
      name: projectName,
      url: href.startsWith('http') ? href : `https://claude.ai${href}`,
    });
  }
  
  return { projects };
}

function discoverClaudeChatsInCurrentProject() {
  const chats = [];
  const seenIds = new Set();
  
  function addChat(link) {
    const href = link.getAttribute('href');
    if (!href || !href.includes('/chat/')) return;
    const match = href.match(/\/chat\/([a-f0-9-]+)/);
    if (!match) return;
    const chatId = match[1];
    if (seenIds.has(chatId)) return;
    seenIds.add(chatId);
    const titleEl = link.querySelector('.truncate.font-base, .font-base, [class*="truncate"]');
    const title = titleEl?.textContent?.trim() || link.textContent?.trim()?.split('\n')[0] || `Chat ${chatId}`;
    chats.push({
      id: chatId,
      title,
      url: href.startsWith('http') ? href : `https://claude.ai${href}`,
    });
  }
  
  function isInsideLeftNav(link) {
    for (const root of leftNavRoots) {
      if (root.contains(link)) return true;
    }
    return false;
  }
  
  const isProjectPage = /\/project\/[a-f0-9-]+/.test(window.location.href);
  
  // Find left nav containers (sidebar with recents)
  const leftNavRoots = [
    ...document.querySelectorAll('aside'),
    ...document.querySelectorAll('nav'),
    ...document.querySelectorAll('[class*="sidebar" i]'),
    ...document.querySelectorAll('[data-testid*="sidebar" i]'),
    ...document.querySelectorAll('[aria-label*="sidebar" i]'),
  ].filter((el) => el && el.isConnected);
  
  if (isProjectPage) {
    // Project is selected: only list chats in the main content. Exclude anything in left nav.
    const allChatLinks = document.querySelectorAll('a[data-dd-action-name="conversation-cell"], a[href^="/chat/"]');
    for (const link of allChatLinks) {
      if (isInsideLeftNav(link)) continue;
      addChat(link);
    }
  } else {
    // No project selected: list chats from the left nav only.
    for (const root of leftNavRoots) {
      root.querySelectorAll('a[data-dd-action-name="conversation-cell"], a[href^="/chat/"]').forEach(addChat);
    }
  }
  
  return { chats };
}

function getCurrentClaudeProject() {
  const url = window.location.href;
  
  // Match: https://claude.ai/project/019ca130-e1a3-7744-b81a-c59ac3b2a31f
  const match = url.match(/\/project\/([a-f0-9-]+)/);
  if (!match) return null;
  
  return {
    id: match[1],
    name: null, // User will provide via UI
  };
}

// ============================================================================
// Perplexity Spaces Discovery
// ============================================================================

function discoverPerplexitySpaces() {
  const spaces = [];
  
  // Look for space cards on perplexity.ai/spaces page
  // Selector: a[href*="/spaces/"] that's not just "/spaces"
  const spaceLinks = document.querySelectorAll('a[href*="/spaces/"]');
  
  for (const link of spaceLinks) {
    const href = link.getAttribute('href');
    if (!href || href === '/spaces') continue;
    
    // Extract space slug-id from URL: /spaces/personal-fitness-weight-loss-tyjqwKgUTX6KVsEIHgLBKA
    const match = href.match(/\/spaces\/([^\/\?]+)/);
    if (!match) continue;
    
    const spaceId = match[1];
    
    // Find space name from link text content
    const spaceName = link.textContent?.trim() || `Space ${spaceId}`;
    
    spaces.push({
      id: spaceId,
      name: spaceName,
      url: href.startsWith('http') ? href : `https://www.perplexity.ai${href}`,
    });
  }
  
  return { spaces };
}

function discoverPerplexityThreadsInCurrentSpace() {
  const threads = [];
  const seenIds = new Set();
  
  function addThread(link) {
    const href = link.getAttribute('href');
    if (!href) return;
    const match = href.match(/\/search\/(.+)/);
    if (!match) return;
    const threadId = match[1];
    if (seenIds.has(threadId)) return;
    seenIds.add(threadId);
    const titleEl = link.querySelector('[data-testid^="thread-title-"]');
    const title = titleEl?.textContent?.trim() || link.textContent?.trim()?.split('\n')[0] || `Thread ${threadId}`;
    threads.push({
      id: threadId,
      title,
      url: href.startsWith('http') ? href : `https://www.perplexity.ai${href}`,
    });
  }
  
  function isInsideLeftNav(link) {
    for (const root of leftNavRoots) {
      if (root.contains(link)) return true;
    }
    return false;
  }
  
  const isSpacePage = /\/spaces\/[^\/]+/.test(window.location.href);
  
  // Find left nav containers (sidebar with all threads)
  const leftNavRoots = [
    ...document.querySelectorAll('aside'),
    ...document.querySelectorAll('nav'),
    ...document.querySelectorAll('[class*="sidebar" i]'),
    ...document.querySelectorAll('[data-testid*="sidebar" i]'),
    ...document.querySelectorAll('[aria-label*="sidebar" i]'),
  ].filter((el) => el && el.isConnected);
  
  if (isSpacePage) {
    // Space is selected: only list threads in the main content. Exclude anything in left nav.
    const allThreadLinks = document.querySelectorAll('a.group[href^="/search/"], a[href^="/search/"]');
    for (const link of allThreadLinks) {
      if (isInsideLeftNav(link)) continue;
      addThread(link);
    }
  } else {
    // No space selected: list threads from the left nav only.
    for (const root of leftNavRoots) {
      root.querySelectorAll('a.group[href^="/search/"], a[href^="/search/"]').forEach(addThread);
    }
  }
  
  return { threads };
}

function getCurrentPerplexitySpace() {
  const url = window.location.href;
  
  // Match: https://www.perplexity.ai/spaces/personal-fitness-weight-loss-tyjqwKgUTX6KVsEIHgLBKA
  const match = url.match(/\/spaces\/([^\/\?]+)/);
  if (!match) return null;
  
  return {
    id: match[1],
    name: null, // User will provide via UI
  };
}

chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
  if (message.action === 'detect') {
    const platform = detectPlatform();
    sendResponse({ platform, supported: platform !== null });
    return;
  }

  if (message.action === 'extract') {
    handleExtraction(message.options || {})
      .then((result) => sendResponse(result))
      .catch((err) => sendResponse({ success: false, error: err.message }));
    return true;
  }

  if (message.action === 'ping') {
    sendResponse({ alive: true });
    return;
  }

  if (message.action === 'waitForConversation') {
    waitForConversationReady(message.options || {})
      .then((result) => sendResponse(result))
      .catch((err) => sendResponse({ ready: false, error: err.message }));
    return true;
  }

  if (message.action === 'discoverProjects') {
    const platform = detectPlatform();
    if (platform === 'chatgpt') {
      sendResponse(discoverChatGPTProjects());
    } else if (platform === 'claude') {
      sendResponse(discoverClaudeProjects());
    } else if (platform === 'perplexity') {
      // Perplexity returns { spaces }, normalize to { projects } for consistency
      const result = discoverPerplexitySpaces();
      sendResponse({ projects: result.spaces || [] });
    } else {
      sendResponse({ error: 'Platform does not support projects/spaces', projects: [] });
    }
    return;
  }

  if (message.action === 'discoverChats') {
    const platform = detectPlatform();
    if (platform === 'chatgpt') {
      sendResponse(discoverChatGPTChatsInCurrentProject());
    } else if (platform === 'claude') {
      sendResponse(discoverClaudeChatsInCurrentProject());
    } else if (platform === 'perplexity') {
      // Perplexity returns { threads }, normalize to { chats } for consistency
      const result = discoverPerplexityThreadsInCurrentSpace();
      sendResponse({ chats: result.threads || [] });
    } else {
      sendResponse({ error: 'Platform does not support projects/spaces', chats: [] });
    }
    return;
  }

  if (message.action === 'getCurrentProject') {
    const platform = detectPlatform();
    if (platform === 'chatgpt') {
      const project = getCurrentChatGPTProject();
      sendResponse({ project });
    } else if (platform === 'claude') {
      const project = getCurrentClaudeProject();
      sendResponse({ project });
    } else if (platform === 'perplexity') {
      const space = getCurrentPerplexitySpace();
      sendResponse({ project: space }); // Use 'project' key for consistency
    } else {
      sendResponse({ project: null });
    }
    return;
  }
});

/**
 * Main extraction pipeline.
 * 1. Platform-specific Pass 0 extraction (clipboard + direct text)
 * 2. Pass 1 heuristics on any uncertain turns
 * 3. Serialize to requested format(s)
 * 4. Download
 */
async function handleExtraction(options) {
  const platform = detectPlatform();
  if (!platform) {
    return { success: false, error: 'Not on a supported chat platform' };
  }

  const format = options.format || 'markdown'; // 'markdown', 'json', 'both'
  console.log(`[Chat Archive] Starting extraction: platform=${platform}, format=${format}`);
  const startTime = Date.now();

  // Save original clipboard content to restore later
  let originalClipboard = '';
  try {
    originalClipboard = await navigator.clipboard.readText();
  } catch {
    // Clipboard inaccessible or empty — ok
  }

  // --- Pass 0: Platform-specific extraction ---
  let extraction;
  try {
    switch (platform) {
      case 'claude':
        extraction = await extractClaudeConversation();
        break;
      case 'chatgpt':
        extraction = await extractChatGPTConversation();
        break;
      case 'gemini':
        extraction = await extractGeminiConversation();
        break;
      case 'grok':
        extraction = await extractGrokConversation();
        break;
      case 'grok-x':
        extraction = await extractGrokXConversation();
        break;
      case 'perplexity':
        extraction = await extractPerplexityConversation();
        break;
      default:
        return { success: false, error: `Unknown platform: ${platform}` };
    }
  } catch (err) {
    console.error('[Chat Archive] Extraction failed:', err);
    // Restore clipboard on error
    try {
      if (originalClipboard) {
        await navigator.clipboard.writeText(originalClipboard);
      }
    } catch {
      // Clipboard restore failed — non-fatal
    }
    return { success: false, error: `Extraction failed: ${err.message}` };
  }

  if (!extraction || extraction.turns.length === 0) {
    // Restore clipboard on error
    try {
      if (originalClipboard) {
        await navigator.clipboard.writeText(originalClipboard);
      }
    } catch {
      // Clipboard restore failed — non-fatal
    }
    return {
      success: false,
      error: 'No conversation turns found. Is there a conversation on this page?',
      errors: extraction?.errors || [],
    };
  }

  // --- Pass 1: Heuristics for uncertain turns ---
  try {
    extraction.turns = applyHeuristics(extraction.turns);
    const heuristicWarnings = heuristicIntegrityCheck(extraction.turns);
    extraction.errors = (extraction.errors || []).concat(heuristicWarnings);
  } catch (err) {
    console.warn('[Chat Archive] Heuristics pass failed (non-fatal):', err);
  }

  // --- Resolve project name (user-supplied only — no inference) ---
  const resolvedProjectName = ('userProjectName' in options) ? (options.userProjectName || null) : null;

  // Runtime assertion: if userProjectName was provided, it must equal what we resolved.
  if ('userProjectName' in options && resolvedProjectName !== (options.userProjectName || null)) {
    throw new Error(
      `[ChatVault] ASSERTION FAILED: projectName mismatch. ` +
      `Passed="${options.userProjectName}", resolved="${resolvedProjectName}"`
    );
  }

  console.log('[ChatVault] Using project name:', resolvedProjectName ?? '(none → Unassigned in filename)');

  // --- Resolve chat name for filename ---
  let resolvedChatName = '';
  let resolvedChatId = '';

  if (platform === 'chatgpt') {
    const currentChatId = window.location.pathname.match(/\/c\/([^\/\?]+)/)?.[1];
    if (currentChatId) {
      resolvedChatId = currentChatId;
      try {
        const { chats } = discoverChatGPTChatsInCurrentProject();
        const current = chats.find((c) => c.id === currentChatId);
        if (current?.title) resolvedChatName = current.title;
      } catch (_) { /* ignore */ }
    }
    if (!resolvedChatName) {
      const fromTitle = document.title?.replace(/\s*[-|]\s*ChatGPT.*$/i, '').trim();
      resolvedChatName = fromTitle || extraction.turns?.find((t) => t.role === 'user')?.content?.slice(0, 60) || '';
    }
  }
  if (platform === 'perplexity') {
    const fromTitle = document.title?.replace(/\s*[-|]\s*Perplexity.*$/i, '').replace(/\s*\|\s*Perplexity.*$/i, '').trim();
    resolvedChatName = fromTitle || extraction.turns?.find((t) => t.role === 'user')?.content?.slice(0, 60) || '';
    resolvedChatId = window.location.pathname || window.location.search?.slice(1) || '';
  }

  const elapsed = Date.now() - startTime;

  // --- skipDownload mode: return raw content for background.js to handle (project export) ---
  // background.js owns all filename logic and download initiation in this mode.
  if (options.skipDownload) {
    try {
      const { markdown, metadata: mdMeta, integrityWarnings: mdWarnings } = serializeToMarkdown(extraction, platform);
      let json = null;
      let jsonMeta = {};
      let jsonWarnings = [];
      if (format === 'both') {
        const r = serializeToJSON(extraction, platform);
        json = r.json;
        jsonMeta = r.metadata;
        jsonWarnings = r.integrityWarnings || [];
      }
      console.log(`[ChatVault] skipDownload extraction complete: ${extraction.turns.length} turns in ${elapsed}ms`);
      
      // Restore original clipboard content
      try {
        if (originalClipboard) {
          await navigator.clipboard.writeText(originalClipboard);
        }
      } catch {
        // Clipboard restore failed — non-fatal
      }
      
      const formatsExported = format === 'both' ? ['markdown', 'json'] : ['markdown'];
      return {
        success: true,
        json,
        markdown,
        chatName: resolvedChatName || null,
        chatId:   resolvedChatId   || null,
        metadata: {
          ...mdMeta,
          ...jsonMeta,
          extraction_time_ms: elapsed,
          formats_exported:   formatsExported,
          source_url:         window.location.href,
        },
        integrityWarnings: [...(mdWarnings || []), ...jsonWarnings],
      };
    } catch (err) {
      // Restore clipboard even on error
      try {
        if (originalClipboard) {
          await navigator.clipboard.writeText(originalClipboard);
        }
      } catch {
        // Clipboard restore failed — non-fatal
      }
      return { success: false, error: `Extraction (skipDownload) failed: ${err.message}` };
    }
  }

  // --- Normal single-chat download path ---
  const downloadResults = [];
  const filenameBase = {
    platform:    platform,
    projectName: resolvedProjectName,
    chatName:    resolvedChatName || null,
    chatId:      resolvedChatId,
  };

  if (format === 'json' || format === 'both') {
    try {
      const { json, metadata, integrityWarnings } = serializeToJSON(extraction, platform);
      const filename = buildExportFilename({ ...filenameBase, ext: 'json' });
      await downloadFile(json, filename, 'application/json');
      downloadResults.push({ format: 'json', metadata, integrityWarnings });
    } catch (err) {
      // Restore clipboard on error
      try {
        if (originalClipboard) {
          await navigator.clipboard.writeText(originalClipboard);
        }
      } catch {
        // Clipboard restore failed — non-fatal
      }
      return { success: false, error: `JSON export failed: ${err.message}` };
    }
  }

  if (format === 'markdown' || format === 'both') {
    try {
      const { markdown, metadata, integrityWarnings } = serializeToMarkdown(extraction, platform);
      const filename = buildExportFilename({ ...filenameBase, ext: 'md' });
      await downloadFile(markdown, filename, 'text/markdown');
      downloadResults.push({ format: 'markdown', metadata, integrityWarnings });
    } catch (err) {
      if (format === 'markdown') {
        // Restore clipboard on error
        try {
          if (originalClipboard) {
            await navigator.clipboard.writeText(originalClipboard);
          }
        } catch {
          // Clipboard restore failed — non-fatal
        }
        return { success: false, error: `Markdown export failed: ${err.message}` };
      }
      console.warn('[Chat Archive] Markdown export failed (JSON succeeded):', err);
    }
  }

  console.log(`[Chat Archive] Export complete: ${extraction.turns.length} turns in ${elapsed}ms`);

  // Restore original clipboard content
  try {
    if (originalClipboard) {
      await navigator.clipboard.writeText(originalClipboard);
    }
  } catch {
    // Clipboard restore failed — non-fatal
  }

  const primaryResult = downloadResults[0] || {};
  return {
    success: true,
    metadata: {
      ...(primaryResult.metadata || {}),
      extraction_time_ms: elapsed,
      formats_exported: downloadResults.map((r) => r.format),
    },
    integrityWarnings: primaryResult.integrityWarnings || [],
  };
}

})();
